### ISSUE TITLE
How to Load in AutoCAD

### ISSUE THREAD

**Issue by ttfreeman** [chasmack/polycalc#1]
Hi,

Just wondering how you load this in AutoCAD. Are you using any other library?

Thanks!

**Comment by chasmack** [comment]
Hi Tony,

Polycalc outputs a DXF 2010 file you can INSERT into your AutoCAD drawing,
or any other drafting or GIS program you might have. Not sure what you mean
regarding libraries. As a Python 3.5 command line utility it uses a few
Python packages, Easydxf and Numpy for example. It's really intended to be
wrapped in some sort of UI. I run it as a page in a Flask based online
tools site where you upload the command file and get back a DXF file and
printed listing. See my Hummaps project.

Hope that helps.

**Comment by ttfreeman** [comment]
That clarifies. Thank you. I'll close the issue then...
